# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="姓名")),
            ],
            options={
                "verbose_name": "姓名库",
                "verbose_name_plural": "姓名库",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="项目名称")),
            ],
            options={
                "verbose_name": "项目库",
                "verbose_name_plural": "项目库",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("project", models.CharField(max_length=200, verbose_name="项目")),
                ("remark", models.TextField(blank=True, default="", verbose_name="工作内容")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="提交时间")),
            ],
            options={
                "verbose_name": "提交记录",
                "verbose_name_plural": "提交记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
